export const CONNET_BUILD_HTML_ASSETS_START = `CONNET_BUILD_HTML_ASSETS_START`;
export const CONNET_BUILD_HTML_ASSETS_SUCCESS = `CONNET_BUILD_HTML_ASSETS_SUCCESS`;
export const CONNET_BUILD_HTML_ASSETS_FAIL = `CONNET_BUILD_HTML_ASSETS_FAIL`;

export const CHANGE_HTML_CODE = `CHANGE_HTML_CODE`;
export const SUBMIT_HTML_CODE = `SUBMIT_HTML_CODE`;

export const RECEIVE_BUILD_HTML_ASSET = `RECEIVE_BUILD_HTML_ASSET`;
